on: [push]
jobs:
  capture_score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn
      - name: run_tests
        run: yarn cy:run
      - name: get_score
        id: score
        uses: warren-sadler/grading-action@v3.2
      - name: report_grade
        run: echo "${{ steps.score.outputs.score }}"
